server {
    add_header X-Frame-Options         "SAMEORIGIN"                      always;
    add_header X-Content-Type-Options  "nosniff"                         always;
    add_header X-XSS-Protection        "1; mode=block"                   always;
    add_header Referrer-Policy         "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self';"             always;

    listen 80 default_server;
    server_name localhost;

    proxy_read_timeout 1000000;
    proxy_connect_timeout 1000000;
    proxy_send_timeout 1000000;

    root .;
    index index.html index.php;

    client_max_body_size 20m;

    location ~ ^/(api|webhook|public) {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location / {
        root public/dist;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_read_timeout 60s;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
