daemon off;
worker_processes 1;
pid storage/framework/nginx/nginx.pid;
error_log storage/logs/nginx.error.log warn;

events {
    worker_connections 1024;
}

http {
    include mime.types;
        default_type application/octet-stream;

        access_log storage/logs/nginx.access.log;

        sendfile on;
        keepalive_timeout 65;

        include default.conf;
}
