daemon off;
worker_processes 1;
pid storage/framework/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    access_log storage/logs/nginx.access.log;
    error_log storage/logs/nginx.error.log;

    sendfile on;
    keepalive_timeout 65;

    include default.conf;
}
