server {
    listen 8080 default_server;
    listen 80 default_server;
    server_name _;

    root /home/site/wwwroot/webroot;
    index index.html index.php;

    location ^~ /storage/ {
        alias /home/site/wwwroot/storage/app/public/;
        try_files $uri $uri/ =404;
        access_log off;
        expires max;
    }

    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ /dist/index.html;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~ \.php$ {
        return 404;
    }
}