server {
    listen 8080 default_server;
    listen 80 default_server;
    server_name _;

    root /home/site/wwwroot/webroot;
    index index.php index.html;

    add_header X-Config-Status "APP-ROUTING-ACTIVE" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}